export const SPORTS = [
  {
    id: "cricket",
    label: "Cricket",
    icon: "🏏",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "football",
    label: "Football",
    icon: "⚽",
    color: "bg-green-50 text-green-700 border-green-200",
  },
  {
    id: "pickleball",
    label: "Pickleball",
    icon: "🏓",
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "padel",
    label: "Padel",
    icon: "🎾",
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
];

export const AREAS = [
  "Satellite",
  "Bopal",
  "Prahlad Nagar",
  "Vastrapur",
  "Thaltej",
  "SG Highway",
  "Maninagar",
  "Navrangpura",
  "Bodakdev",
  "Chandkheda",
  "Gota",
  "Motera",
];

export const VENUES = [
  {
    id: "v1",
    name: "Arena Cricket Hub",
    sport: "cricket",
    area: "Satellite",
    address: "Near Shivranjani Cross Road, Satellite, Ahmedabad",
    pricePerHour: 800,
    rating: 4.7,
    reviewCount: 124,
    image: "/venues/cricket-turf.png",
    amenities: [
      "Floodlights",
      "Parking",
      "Changing Room",
      "Canteen",
      "First Aid",
    ],
    openTime: "06:00",
    closeTime: "23:00",
    availableSlots: [
      "06:00",
      "07:00",
      "08:00",
      "16:00",
      "17:00",
      "19:00",
      "20:00",
      "21:00",
    ],
    description:
      "Premium indoor cricket turf with high-quality artificial grass and professional nets. Perfect for practice sessions and friendly matches.",
    coordinates: { lat: 23.0254, lng: 72.5092 },
  },
  {
    id: "v2",
    name: "GreenField Cricket Turf",
    sport: "cricket",
    area: "Bopal",
    address: "Bopal-Ghuma Road, Bopal, Ahmedabad",
    pricePerHour: 700,
    rating: 4.5,
    reviewCount: 89,
    image: "/venues/cricket-turf.png",
    amenities: ["Floodlights", "Parking", "Changing Room", "Drinking Water"],
    openTime: "05:30",
    closeTime: "22:00",
    availableSlots: [
      "05:30",
      "06:00",
      "07:00",
      "08:00",
      "18:00",
      "19:00",
      "20:00",
    ],
    description:
      "Affordable cricket turf in the heart of Bopal with excellent facilities and ample parking. Great for evening practice.",
    coordinates: { lat: 23.0395, lng: 72.4782 },
  },
  {
    id: "v3",
    name: "ProKick Football Arena",
    sport: "football",
    area: "Prahlad Nagar",
    address: "Prahlad Nagar Garden Road, Ahmedabad",
    pricePerHour: 1200,
    rating: 4.8,
    reviewCount: 203,
    image: "/venues/football-turf.png",
    amenities: [
      "Floodlights",
      "Valet Parking",
      "Changing Room",
      "Canteen",
      "Shower",
      "CCTV",
    ],
    openTime: "06:00",
    closeTime: "24:00",
    availableSlots: [
      "06:00",
      "07:00",
      "09:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
    ],
    description:
      "Ahmedabad&apos;s most premium football turf with FIFA-grade artificial grass. Hosts weekend leagues and corporate events.",
    coordinates: { lat: 23.0148, lng: 72.5083 },
  },
  {
    id: "v4",
    name: "Goal Zone Football Ground",
    sport: "football",
    area: "Vastrapur",
    address: "Vastrapur Lake Road, Vastrapur, Ahmedabad",
    pricePerHour: 1000,
    rating: 4.4,
    reviewCount: 156,
    image: "/venues/football-turf.png",
    amenities: ["Floodlights", "Parking", "Changing Room", "Canteen"],
    openTime: "05:00",
    closeTime: "23:00",
    availableSlots: [
      "05:00",
      "06:00",
      "07:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
    description:
      "Well-maintained football turf near Vastrapur lake. Popular for morning and evening sessions with friendly atmosphere.",
    coordinates: { lat: 23.0364, lng: 72.5266 },
  },
  {
    id: "v5",
    name: "PickleZone Courts",
    sport: "pickleball",
    area: "Thaltej",
    address: "Thaltej Cross Road, Near S.G. Highway, Ahmedabad",
    pricePerHour: 600,
    rating: 4.9,
    reviewCount: 67,
    image: "/venues/pickleball-court.png",
    amenities: [
      "Outdoor Courts",
      "Parking",
      "Locker Room",
      "Equipment Rental",
      "Coach Available",
    ],
    openTime: "06:00",
    closeTime: "22:00",
    availableSlots: [
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
    description:
      "Gujarat's best dedicated pickleball facility with 4 professional courts. Coaching sessions available on weekends.",
    coordinates: { lat: 23.0547, lng: 72.5128 },
  },
  {
    id: "v6",
    name: "AhmedaBall Pickleball Club",
    sport: "pickleball",
    area: "Bodakdev",
    address: "Judges Bungalow Road, Bodakdev, Ahmedabad",
    pricePerHour: 550,
    rating: 4.6,
    reviewCount: 43,
    image: "/venues/pickleball-court.png",
    amenities: [
      "Indoor Courts",
      "Parking",
      "Changing Room",
      "Equipment Rental",
    ],
    openTime: "07:00",
    closeTime: "21:00",
    availableSlots: [
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
    description:
      "Newly opened indoor pickleball club in Bodakdev. Air-conditioned courts with premium flooring for year-round play.",
    coordinates: { lat: 23.0437, lng: 72.5278 },
  },
  {
    id: "v7",
    name: "Padel Pro Ahmedabad",
    sport: "padel",
    area: "SG Highway",
    address: "Sola Road, Near S.G. Highway, Ahmedabad",
    pricePerHour: 1500,
    rating: 4.9,
    reviewCount: 38,
    image: "/venues/padel-court.png",
    amenities: [
      "Glass Courts",
      "AC Lounge",
      "Pro Shop",
      "Coaching",
      "Parking",
      "Cafeteria",
    ],
    openTime: "06:00",
    closeTime: "23:00",
    availableSlots: [
      "06:00",
      "07:00",
      "09:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
    description:
      "Ahmedabad's first world-class padel facility with panoramic glass courts. Professional coaches available daily.",
    coordinates: { lat: 23.0601, lng: 72.5209 },
  },
  {
    id: "v8",
    name: "Navkar Padel Club",
    sport: "padel",
    area: "Chandkheda",
    address: "Chandkheda Char Rasta, Gandhinagar Highway, Ahmedabad",
    pricePerHour: 1200,
    rating: 4.5,
    reviewCount: 29,
    image: "/venues/padel-court.png",
    amenities: ["Glass Courts", "Parking", "Changing Room", "Equipment Rental"],
    openTime: "05:30",
    closeTime: "22:00",
    availableSlots: [
      "05:30",
      "06:00",
      "07:00",
      "08:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
    description:
      "Affordable padel courts in North Ahmedabad. Great for beginners and regular players alike with friendly community.",
    coordinates: { lat: 23.115, lng: 72.5997 },
  },
  {
    id: "v9",
    name: "Motera Cricket Hub",
    sport: "cricket",
    area: "Motera",
    address: "Near Narendra Modi Stadium, Motera, Ahmedabad",
    pricePerHour: 900,
    rating: 4.6,
    reviewCount: 112,
    image: "/venues/cricket-turf.png",
    amenities: [
      "Floodlights",
      "Parking",
      "Changing Room",
      "Canteen",
      "Ball Machine",
    ],
    openTime: "05:00",
    closeTime: "23:00",
    availableSlots: [
      "05:00",
      "06:00",
      "07:00",
      "08:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
    ],
    description:
      "Located near the iconic Narendra Modi Stadium, this premium turf offers a world-class cricket experience for enthusiasts.",
    coordinates: { lat: 23.1026, lng: 72.5957 },
  },
  {
    id: "v10",
    name: "Navrangpura Football Hub",
    sport: "football",
    area: "Navrangpura",
    address: "University Road, Navrangpura, Ahmedabad",
    pricePerHour: 950,
    rating: 4.3,
    reviewCount: 87,
    image: "/venues/football-turf.png",
    amenities: ["Floodlights", "Parking", "Changing Room", "Drinking Water"],
    openTime: "06:00",
    closeTime: "22:00",
    availableSlots: [
      "06:00",
      "07:00",
      "08:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
    ],
    description:
      "Central Ahmedabad football turf popular among college students and young professionals for evening kickabouts.",
    coordinates: { lat: 23.0301, lng: 72.5594 },
  },
];

export const PLAYERS = [
  {
    id: "p1",
    name: "Arjun Mehta",
    age: 24,
    sport: "cricket",
    position: "Batsman",
    area: "Satellite",
    level: "Advanced",
    availability: ["Evening", "Weekend"],
    avatar: "AM",
    bio: "Passionate cricketer looking for competitive matches and practice sessions.",
    gamesPlayed: 87,
    joinedDate: "2024-03",
  },
  {
    id: "p2",
    name: "Riya Shah",
    age: 22,
    sport: "pickleball",
    position: "All-rounder",
    area: "Thaltej",
    level: "Intermediate",
    availability: ["Morning", "Weekend"],
    avatar: "RS",
    bio: "Pickleball enthusiast, started 1 year ago and loving the sport!",
    gamesPlayed: 34,
    joinedDate: "2024-06",
  },
  {
    id: "p3",
    name: "Dev Patel",
    age: 27,
    sport: "football",
    position: "Midfielder",
    area: "Prahlad Nagar",
    level: "Advanced",
    availability: ["Evening", "Weekend", "Morning"],
    avatar: "DP",
    bio: "Former college football player looking for weekend leagues and casual matches.",
    gamesPlayed: 145,
    joinedDate: "2023-11",
  },
  {
    id: "p4",
    name: "Priya Desai",
    age: 30,
    sport: "padel",
    position: "Doubles",
    area: "SG Highway",
    level: "Pro",
    availability: ["Morning", "Evening"],
    avatar: "PD",
    bio: "Padel coach and enthusiast. Looking for competitive doubles partners.",
    gamesPlayed: 210,
    joinedDate: "2023-08",
  },
  {
    id: "p5",
    name: "Karan Joshi",
    age: 21,
    sport: "cricket",
    position: "Fast Bowler",
    area: "Bopal",
    level: "Intermediate",
    availability: ["Morning", "Weekend"],
    avatar: "KJ",
    bio: "Aggressive fast bowler, can bowl at 120+ km/h. Looking for serious teams.",
    gamesPlayed: 52,
    joinedDate: "2024-01",
  },
  {
    id: "p6",
    name: "Nisha Trivedi",
    age: 26,
    sport: "football",
    position: "Striker",
    area: "Vastrapur",
    level: "Intermediate",
    availability: ["Evening", "Weekend"],
    avatar: "NT",
    bio: "Love football and looking for a mixed-gender team. Play twice a week.",
    gamesPlayed: 78,
    joinedDate: "2024-02",
  },
  {
    id: "p7",
    name: "Rohan Bhatt",
    age: 35,
    sport: "padel",
    position: "Singles",
    area: "Bodakdev",
    level: "Beginner",
    availability: ["Weekend"],
    avatar: "RB",
    bio: "New to padel, looking for friendly games and coaching sessions.",
    gamesPlayed: 8,
    joinedDate: "2024-09",
  },
  {
    id: "p8",
    name: "Siddhi Kapoor",
    age: 23,
    sport: "pickleball",
    position: "Singles & Doubles",
    area: "Navrangpura",
    level: "Advanced",
    availability: ["Morning", "Evening", "Weekend"],
    avatar: "SK",
    bio: "Competitive pickleball player looking for ranked matches and tournaments.",
    gamesPlayed: 96,
    joinedDate: "2023-12",
  },
  {
    id: "p9",
    name: "Manav Solanki",
    age: 29,
    sport: "cricket",
    position: "Wicketkeeper",
    area: "Motera",
    level: "Advanced",
    availability: ["Morning", "Evening"],
    avatar: "MS",
    bio: "WK-Batsman near Motera. Part of local club, always looking for extra matches.",
    gamesPlayed: 134,
    joinedDate: "2023-09",
  },
  {
    id: "p10",
    name: "Ananya Sharma",
    age: 25,
    sport: "football",
    position: "Goalkeeper",
    area: "Gota",
    level: "Intermediate",
    availability: ["Evening", "Weekend"],
    avatar: "AS",
    bio: "Goalkeeper with 5 years experience. Looking for competitive 7-a-side teams.",
    gamesPlayed: 110,
    joinedDate: "2024-01",
  },
];

export const TEAMS = [
  {
    id: "t1",
    name: "Satellite Strikers",
    sport: "cricket",
    area: "Satellite",
    level: "Advanced",
    members: 9,
    maxMembers: 11,
    avatar: "SS",
    captain: "Arjun Mehta",
    description:
      "Competitive cricket team from Satellite area. We play weekend tournaments and host monthly matches.",
    wins: 23,
    losses: 7,
    lookingFor: "Spinner and Batsman",
    createdDate: "2023-06",
  },
  {
    id: "t2",
    name: "Bopal Blasters",
    sport: "football",
    area: "Bopal",
    level: "Intermediate",
    members: 10,
    maxMembers: 14,
    avatar: "BB",
    captain: "Dev Patel",
    description:
      "Fun-loving football team that plays on weekends. All skill levels welcome, focus on enjoyment.",
    wins: 15,
    losses: 12,
    lookingFor: "Defender and Goalkeeper",
    createdDate: "2023-09",
  },
  {
    id: "t3",
    name: "PK Warriors",
    sport: "pickleball",
    area: "Thaltej",
    level: "Pro",
    members: 4,
    maxMembers: 6,
    avatar: "PW",
    captain: "Riya Shah",
    description:
      "Competitive pickleball team aiming for Gujarat state championship. Looking for serious players.",
    wins: 18,
    losses: 4,
    lookingFor: "Mixed doubles partner",
    createdDate: "2024-01",
  },
  {
    id: "t4",
    name: "Padel Kings",
    sport: "padel",
    area: "SG Highway",
    level: "Advanced",
    members: 3,
    maxMembers: 4,
    avatar: "PK",
    captain: "Priya Desai",
    description:
      "Competitive padel doubles team. We train 3x a week and participate in city-level tournaments.",
    wins: 31,
    losses: 9,
    lookingFor: "1 more doubles partner",
    createdDate: "2023-07",
  },
  {
    id: "t5",
    name: "Motera Cricket Club",
    sport: "cricket",
    area: "Motera",
    level: "Pro",
    members: 11,
    maxMembers: 15,
    avatar: "MC",
    captain: "Manav Solanki",
    description:
      "Established cricket club near Narendra Modi Stadium. District-level tournament participants.",
    wins: 45,
    losses: 12,
    lookingFor: "Substitute players",
    createdDate: "2022-11",
  },
  {
    id: "t6",
    name: "Goal Getters AFC",
    sport: "football",
    area: "Prahlad Nagar",
    level: "Advanced",
    members: 12,
    maxMembers: 16,
    avatar: "GG",
    captain: "Nisha Trivedi",
    description:
      "Mixed-gender football club focused on competitive 7-a-side and 11-a-side tournaments.",
    wins: 28,
    losses: 14,
    lookingFor: "Striker and Central Midfielder",
    createdDate: "2023-04",
  },
];

export const TIME_SLOTS = [
  "05:00",
  "05:30",
  "06:00",
  "06:30",
  "07:00",
  "07:30",
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
];

export function getSportColor(sport) {
  const map = {
    cricket: "bg-amber-100 text-amber-800",
    football: "bg-green-100 text-green-800",
    pickleball: "bg-blue-100 text-blue-800",
    padel: "bg-orange-100 text-orange-800",
  };
  return map[sport];
}

// Direct messaging is only enabled for pickleball and padel players.
export function canMessage(sport) {
  return sport === "pickleball" || sport === "padel";
}

export function getLevelColor(level) {
  const map = {
    Beginner: "bg-slate-100 text-slate-700",
    Intermediate: "bg-blue-100 text-blue-700",
    Advanced: "bg-primary/10 text-primary",
    Pro: "bg-amber-100 text-amber-700",
  };
  return map[level] ?? "bg-slate-100 text-slate-700";
}
