"""
Django settings for playmates_backend project.

Generated by Antigravity for a modern React + Django + MongoDB college project.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-playmates-backend-secret-key-for-college-project'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts during local development testing
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # CORS Header support for React Vite dev server
    'corsheaders',
    
    # Custom REST API App
    'api',

    # Default Django core apps (required for base startup)
    'django.contrib.contenttypes',
    'django.contrib.auth',
]

MIDDLEWARE = [
    # CorsMiddleware must be at the very top to intercepts requests before views
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'playmates_backend.urls'

WSGI_APPLICATION = 'playmates_backend.wsgi.application'

# Database configuration
# Since we are using PyMongo to query MongoDB directly, we do not need Django ORM database support.
# Setting it to dummy avoids requirement of SQLite/PostgreSQL drivers.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata' # Indian Local Time
USE_I18N = True
USE_TZ = True

# CORS Origin Allowances
# Allows your React client (http://localhost:3000) to fetch endpoints from Django (http://localhost:8000)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Template engines configuration to load built React index.html template
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'dist'], # Point to Vite build folder
        'APP_DIRS': True,
    },
]

